<a href="https://colab.research.google.com/github/priyxnshu07/UCS420/blob/main/LABASSIGNMENT4cognitive_computing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Q.1 Write a program to create a NumPy 1D-array with 5 elements and perform basic
operations like:
a) Addition of 2 in all the element
b) Multiply 3 with all the elements
c) Divide every element by 2

In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5])
add_result= arr+2
multiplication_result = arr*3
division_result=arr/2
print("ORIGINAL ARRAY:",arr)
print("ADDITION:",add_result)
print("MULTIPLICATION:",multiplication_result)
print("DIVISION:",division_result)

Q.2 Questions on Basic NumPy Array:
a) Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5])
b) Find the most frequent value and their indice(s) in the following arrays:
i. x = np.array([1,2,3,4,5,1,2,1,1,1])
ii. y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])

In [3]:
#a) Reverse the array
import numpy as np

arr = np.array([1, 2, 3, 6, 4, 5])
reversed_arr = arr[::-1]

print("Reversed array:", reversed_arr)

#b)
x = np.array([1,2,3,4,5,1,2,1,1,1])
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])


most_frequent_x = np.bincount(x).argmax()
most_frequent_y = np.bincount(y).argmax()


indices_x = np.where(x == most_frequent_x)[0]
indices_y = np.where(y == most_frequent_y)[0]

print("Most frequent value in x:", most_frequent_x, "at indices", indices_x)
print("Most frequent value in y:", most_frequent_y, "at indices", indices_y)


Reversed array: [5 4 6 3 2 1]
Most frequent value in x: 1 at indices [0 5 7 8 9]
Most frequent value in y: 1 at indices [0 1 2]


Q.3 For the given 2-D array arr=np.array([10, 20, 30], [40, 50, 60], [70, 80, 90]), access
elements using row and column indices as follows:
a) Access 1st row, 2nd column
b) Access 3rd row, 1st column

In [4]:
# Creating a 2D array
arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])

# a) Access 1st row, 2nd column
val_1 = arr[0, 1]

# b) Access 3rd row, 1st column
val_2 = arr[2, 0]

print("1st row, 2nd column:", val_1)
print("3rd row, 1st column:", val_2)


1st row, 2nd column: 20
3rd row, 1st column: 70


Q.4 Write program to create an 1-D NumPy array named <<Your Name>> with evenly
spaced 25 numbers from 10 to 100 using linspace(). Print the dimensions of the array,
shape, total elements, the data type of each element and total number of bytes consumed
by the array. Find the transpose of this array using reshape() attribute. Can we do the same
with T attribute?

In [5]:
# Replace <<Your Name>> with your name, e.g., "Priyanshu"
arr = np.linspace(10, 100, 25)

# Printing details
print("Array:", arr)
print("Dimensions:", arr.ndim)
print("Shape:", arr.shape)
print("Total elements:", arr.size)
print("Data type:", arr.dtype)
print("Total bytes:", arr.nbytes)

# Reshaping to transpose
transposed_arr = arr.reshape(25, 1)

print("Transposed array shape:", transposed_arr.shape)

#Yes, we can also use .T for transposing, but since it’s a 1D array, .T will not change the shape.



Array: [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
Dimensions: 1
Shape: (25,)
Total elements: 25
Data type: float64
Total bytes: 200
Transposed array shape: (25, 1)


Q5.Create a 2-D Array of three rows and four columns, named ucs420_<your_name>>
with following values – 10, 20, 30, 40, 50, 60, 70, 80, 90, 15, 20, 35. Compute the mean,
median, max, min, unique elements. Reshape the array to four rows and three columns and
name it as reshaped_ ucs420_<your_name>>. Resize the array to two rows and three
columns and name it as resized_ ucs420_<your_name>>.

In [7]:
# Creating the 2D array
arr = np.array([[10, 20, 30, 40], [50, 60, 70, 80], [90, 15, 20, 35]])

# Computing statistics
mean_val = np.mean(arr)
median_val = np.median(arr)
max_val = np.max(arr)
min_val = np.min(arr)
unique_elements = np.unique(arr)

print("Mean:", mean_val)
print("Median:", median_val)
print("Max:", max_val)
print("Min:", min_val)
print("Unique elements:", unique_elements)

# Reshaping the array to 4x3
reshaped_arr = arr.reshape(4, 3)
print("Reshaped array:\n", reshaped_arr)

# Resizing the array to 2x3
resized_arr = np.resize(arr, (2, 3))
print("Resized array:\n", resized_arr)



Mean: 43.333333333333336
Median: 37.5
Max: 90
Min: 10
Unique elements: [10 15 20 30 35 40 50 60 70 80 90]
Reshaped array:
 [[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]
Resized array:
 [[10 20 30]
 [40 50 60]]
